# --- DEVELOPMENT DOCKERFILE ---

FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

# Устанавливаем ts-node-dev для автоперезапуска
RUN npm install -g ts-node-dev

EXPOSE 8080

CMD ["ts-node-dev", "--respawn", "--transpile-only", "src/main.ts"]
